### ISSUE TITLE
Why missing files

### ISSUE THREAD

**Issue by fangxing123** [daneshtarapore/argos3-foraging#1]
fatal error: argos3/plugins/robots/e-puck/control_interface/ci_epuck_proximity_sensor.h: No such file or directory

**Comment by daneshtarapore** [comment]
Proximity sensors for the e-puck are yet to be incorporated into the ARGoS simulator. For the fault-detection algorithms that can work with the current version of ARGoS, please see https://github.com/daneshtarapore/faultdetection-epuckswarm.git

**Comment by fangxing123** [comment]
thanks
